#!/usr/bin/env bash
# recon-agent quick install — generated by the hub.
# Idempotent: every step skips when its target already exists.
set -euo pipefail

TOKEN="__TOKEN__"
AGENT_ID="__AGENT_ID__"
HUB_ENDPOINT="__HUB_ENDPOINT__"
VERSION="__VERSION__"
DOWNLOAD_BASE="__DOWNLOAD_BASE__"

PREFIX=/usr/local/bin
STATE_DIR=/var/lib/recon
CONF_DIR=/etc/recon
SVC_NAME=recon-agent

log() { printf "==> %s\n" "$*"; }
die() { printf "!!! %s\n" "$*" >&2; exit 1; }

# ── pre-flight ──────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "run as root (sudo)"
command -v systemctl >/dev/null || die "systemd is required"
command -v curl >/dev/null     || die "curl is required (apt install curl)"

# Map uname -m to the release naming.
case "$(uname -m)" in
  x86_64|amd64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) die "unsupported arch $(uname -m)" ;;
esac
log "arch: $ARCH · version: $VERSION · hub: $HUB_ENDPOINT · agent_id: $AGENT_ID"

# ── recon user ──────────────────────────────────────────────────────────────
if ! id recon &>/dev/null; then
  log "creating recon user"
  useradd --system --home "$STATE_DIR" --shell /usr/sbin/nologin --user-group recon
  usermod -aG adm,systemd-journal recon || true
fi
install -d -m 0750 -o recon -g recon "$STATE_DIR"
install -d -m 0755 "$CONF_DIR"

# ── binary ──────────────────────────────────────────────────────────────────
TARBALL="recon-agent-${VERSION}-linux-${ARCH}.tar.gz"
URL="${DOWNLOAD_BASE}/${TARBALL}"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

if [[ ! -x "${PREFIX}/recon-agent" ]]; then
  log "downloading $URL"
  curl -fsSL "$URL" -o "$TMP/${TARBALL}"
  tar -xzf "$TMP/${TARBALL}" -C "$TMP"
  install -m 0755 "$TMP"/*/bin/recon-agent "${PREFIX}/recon-agent"
else
  log "binary already present at ${PREFIX}/recon-agent — skipping download"
fi

# ── bootstrap token ─────────────────────────────────────────────────────────
TOK_FILE="${STATE_DIR}/bootstrap.token"
if [[ ! -s "$TOK_FILE" && ! -s "${STATE_DIR}/agent.pem" ]]; then
  log "writing bootstrap token (single-use)"
  install -m 0600 -o recon -g recon /dev/null "$TOK_FILE"
  printf '%s' "$TOKEN" > "$TOK_FILE"
fi

# ── config ──────────────────────────────────────────────────────────────────
CONF="${CONF_DIR}/agent.yaml"
if [[ ! -f "$CONF" ]]; then
  log "writing $CONF"
  cat > "$CONF" <<EOF
hub:
  endpoint: "${HUB_ENDPOINT}"
  ca_cert:  ${STATE_DIR}/hub-ca.pem
  cert:     ${STATE_DIR}/agent.pem
  key:      ${STATE_DIR}/agent.key
  bootstrap_token: ${TOK_FILE}
  server_name: ${HUB_ENDPOINT%%:*}

identity:
  id: ${AGENT_ID}
  labels:
    host: $(hostname)
    os:   $(. /etc/os-release 2>/dev/null && echo "${ID:-linux}")

runtime:
  max_concurrent_collectors: 4
  artifact_dir: ${STATE_DIR}/artifacts
  default_timeout: 30s
  heartbeat_interval: 15s
EOF
  chmod 0644 "$CONF"
else
  log "config $CONF already present — skipping"
fi

# ── systemd unit ────────────────────────────────────────────────────────────
UNIT=/etc/systemd/system/${SVC_NAME}.service
if [[ ! -f "$UNIT" ]]; then
  log "writing systemd unit"
  cat > "$UNIT" <<EOF
[Unit]
Description=Recon agent — read-only diagnostic data collector
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=recon
Group=recon
SupplementaryGroups=adm systemd-journal
ExecStart=${PREFIX}/recon-agent --config ${CONF}
Restart=on-failure
RestartSec=5s

ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
NoNewPrivileges=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
ReadWritePaths=${STATE_DIR}

CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_SYS_PTRACE CAP_NET_RAW
AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_SYS_PTRACE CAP_NET_RAW

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
fi

# ── start ───────────────────────────────────────────────────────────────────
log "enabling + starting ${SVC_NAME}"
systemctl enable --now "${SVC_NAME}"

sleep 2
if systemctl is-active --quiet "${SVC_NAME}"; then
  log "ok — ${SVC_NAME} is running"
  log "logs: journalctl -u ${SVC_NAME} -f"
else
  log "service not active — last log lines:"
  journalctl -u "${SVC_NAME}" --no-pager -n 30 || true
  exit 1
fi
