#!/usr/bin/env bash
# recon-agent quick install — generated by the hub.
# Idempotent: every step skips when its target already exists.
set -euo pipefail

TOKEN="__TOKEN__"
AGENT_ID="__AGENT_ID__"
HUB_ENDPOINT="__HUB_ENDPOINT__"
VERSION="__VERSION__"
DOWNLOAD_BASE="__DOWNLOAD_BASE__"

PREFIX=/usr/local/bin
STATE_DIR=/var/lib/recon
CONF_DIR=/etc/recon
SVC_NAME=recon-agent

log() { printf "==> %s\n" "$*"; }
die() { printf "!!! %s\n" "$*" >&2; exit 1; }

# ── pre-flight ──────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "run as root (sudo)"
command -v systemctl >/dev/null || die "systemd is required"
command -v curl >/dev/null     || die "curl is required (apt install curl)"

# Map uname -m to the release naming.
case "$(uname -m)" in
  x86_64|amd64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) die "unsupported arch $(uname -m)" ;;
esac
log "arch: $ARCH · version: $VERSION · hub: $HUB_ENDPOINT · agent_id: $AGENT_ID"

# ── recon user ──────────────────────────────────────────────────────────────
if ! id recon &>/dev/null; then
  log "creating recon user"
  useradd --system --home "$STATE_DIR" --shell /usr/sbin/nologin --user-group recon
  usermod -aG adm,systemd-journal recon || true
fi
install -d -m 0750 -o recon -g recon "$STATE_DIR"
install -d -m 0755 "$CONF_DIR"

# Re-running the installer is the operator's "clean reinstall" lever:
# stop the service (if any) and wipe the prior identity so the new
# token + new endpoint are honoured, instead of crash-looping or
# silently retrying with a stale CA / cert.
log "stopping prior recon-agent (if any) + wiping stale identity"
systemctl stop "${SVC_NAME}" 2>/dev/null || true
rm -f "${STATE_DIR}/agent.pem" "${STATE_DIR}/agent.key" "${STATE_DIR}/hub-ca.pem"

# ── binary ──────────────────────────────────────────────────────────────────
TARBALL="recon-agent-linux-${ARCH}.tar.gz"
URL="${DOWNLOAD_BASE}/${TARBALL}"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

log "downloading $URL"
curl -fsSL "$URL" -o "$TMP/${TARBALL}"
tar -xzf "$TMP/${TARBALL}" -C "$TMP"
install -m 0755 "$TMP"/*/bin/recon-agent "${PREFIX}/recon-agent"

# ── bootstrap token ─────────────────────────────────────────────────────────
TOK_FILE="${STATE_DIR}/bootstrap.token"
log "writing bootstrap token (single-use)"
install -m 0600 -o recon -g recon /dev/null "$TOK_FILE"
printf '%s' "$TOKEN" > "$TOK_FILE"

# ── config ──────────────────────────────────────────────────────────────────
# Always rewrite — operators rerun the installer to fix a misconfigured
# endpoint / agent_id / version, so silently keeping the old config would
# defeat the whole purpose. State files (cert, token) live in $STATE_DIR
# and survive across reinstalls; the config is fully derived from the
# install URL and is cheap to regenerate.
CONF="${CONF_DIR}/agent.yaml"
log "writing $CONF"
cat > "$CONF" <<EOF
hub:
  endpoint: "${HUB_ENDPOINT}"
  ca_cert:  ${STATE_DIR}/hub-ca.pem
  cert:     ${STATE_DIR}/agent.pem
  key:      ${STATE_DIR}/agent.key
  bootstrap_token: ${TOK_FILE}
  server_name: ${HUB_ENDPOINT%%:*}

identity:
  id: ${AGENT_ID}
  labels:
    host: $(hostname)
    os:   $(. /etc/os-release 2>/dev/null && echo "${ID:-linux}")

runtime:
  max_concurrent_collectors: 4
  artifact_dir: ${STATE_DIR}/artifacts
  default_timeout: 30s
  heartbeat_interval: 15s
EOF
chmod 0644 "$CONF"

# ── systemd unit ────────────────────────────────────────────────────────────
UNIT=/etc/systemd/system/${SVC_NAME}.service
if [[ ! -f "$UNIT" ]]; then
  log "writing systemd unit"
  cat > "$UNIT" <<EOF
[Unit]
Description=Recon agent — read-only diagnostic data collector
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=recon
Group=recon
SupplementaryGroups=adm systemd-journal
ExecStart=${PREFIX}/recon-agent --config ${CONF}
Restart=on-failure
RestartSec=5s

ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
NoNewPrivileges=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallArchitectures=native
ReadWritePaths=${STATE_DIR}

CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_SYS_PTRACE CAP_NET_RAW
AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_SYS_PTRACE CAP_NET_RAW

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
fi

# ── start ───────────────────────────────────────────────────────────────────
# Capture the start moment so we can scope journalctl to logs produced by
# this run only — otherwise we'd dump stale lines from the prior failed
# attempt and confuse the operator.
START_TS=$(date '+%Y-%m-%d %H:%M:%S')

log "enabling + starting ${SVC_NAME}"
systemctl enable --now "${SVC_NAME}"

# Give the agent a few seconds to either succeed (hello sent) or surface
# its first error in the journal. 6s is enough for the gRPC handshake +
# 1-2 backoff iterations on a DNS / firewall / TLS failure.
sleep 6
log "logs since start of this install:"
journalctl -u "${SVC_NAME}" --no-pager --since "$START_TS" || true

if systemctl is-active --quiet "${SVC_NAME}"; then
  log "ok — ${SVC_NAME} is running"
  log "follow: journalctl -u ${SVC_NAME} -f"
else
  log "service not active — see logs above"
  exit 1
fi
