// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/recon.proto

package reconpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERROR       Status = 2
	Status_STATUS_TIMEOUT     Status = 3
	Status_STATUS_CANCELED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_TIMEOUT",
		4: "STATUS_CANCELED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_TIMEOUT":     3,
		"STATUS_CANCELED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_recon_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_internal_proto_recon_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{0}
}

type EnrollRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CsrPem         []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_internal_proto_recon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *EnrollRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	HubCaPem      []byte                 `protobuf:"bytes,2,opt,name=hub_ca_pem,json=hubCaPem,proto3" json:"hub_ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_internal_proto_recon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *EnrollResponse) GetHubCaPem() []byte {
	if x != nil {
		return x.HubCaPem
	}
	return nil
}

type AgentMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMsg_Hello
	//	*AgentMsg_Heartbeat
	//	*AgentMsg_Result
	//	*AgentMsg_Artifact
	Payload       isAgentMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMsg) Reset() {
	*x = AgentMsg{}
	mi := &file_internal_proto_recon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMsg) ProtoMessage() {}

func (x *AgentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMsg.ProtoReflect.Descriptor instead.
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMsg) GetPayload() isAgentMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMsg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMsg) GetResult() *CollectResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMsg) GetArtifact() *ArtifactChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Artifact); ok {
			return x.Artifact
		}
	}
	return nil
}

type isAgentMsg_Payload interface {
	isAgentMsg_Payload()
}

type AgentMsg_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMsg_Result struct {
	Result *CollectResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type AgentMsg_Artifact struct {
	Artifact *ArtifactChunk `protobuf:"bytes,4,opt,name=artifact,proto3,oneof"`
}

func (*AgentMsg_Hello) isAgentMsg_Payload() {}

func (*AgentMsg_Heartbeat) isAgentMsg_Payload() {}

func (*AgentMsg_Result) isAgentMsg_Payload() {}

func (*AgentMsg_Artifact) isAgentMsg_Payload() {}

type HubMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubMsg_Collect
	//	*HubMsg_Cancel
	//	*HubMsg_Config
	Payload       isHubMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMsg) Reset() {
	*x = HubMsg{}
	mi := &file_internal_proto_recon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMsg) ProtoMessage() {}

func (x *HubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMsg.ProtoReflect.Descriptor instead.
func (*HubMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{3}
}

func (x *HubMsg) GetPayload() isHubMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubMsg) GetCollect() *CollectRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMsg_Collect); ok {
			return x.Collect
		}
	}
	return nil
}

func (x *HubMsg) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMsg_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *HubMsg) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*HubMsg_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isHubMsg_Payload interface {
	isHubMsg_Payload()
}

type HubMsg_Collect struct {
	Collect *CollectRequest `protobuf:"bytes,1,opt,name=collect,proto3,oneof"`
}

type HubMsg_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type HubMsg_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

func (*HubMsg_Collect) isHubMsg_Payload() {}

func (*HubMsg_Cancel) isHubMsg_Payload() {}

func (*HubMsg_Config) isHubMsg_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Collectors    []*CollectorManifest   `protobuf:"bytes,4,rep,name=collectors,proto3" json:"collectors,omitempty"`
	Facts         map[string]string      `protobuf:"bytes,5,rep,name=facts,proto3" json:"facts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // auto-facts (os, kernel, primary_ip, ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_proto_recon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetCollectors() []*CollectorManifest {
	if x != nil {
		return x.Collectors
	}
	return nil
}

func (x *Hello) GetFacts() map[string]string {
	if x != nil {
		return x.Facts
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UptimeS       int64                  `protobuf:"varint,2,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	TsUnix        int64                  `protobuf:"varint,3,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_proto_recon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetUptimeS() int64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *Heartbeat) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

type CollectorManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Reads         []string               `protobuf:"bytes,5,rep,name=reads,proto3" json:"reads,omitempty"`
	Requires      []string               `protobuf:"bytes,6,rep,name=requires,proto3" json:"requires,omitempty"`
	ParamsSchema  []byte                 `protobuf:"bytes,7,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"` // JSON schema bytes
	OutputSchema  []byte                 `protobuf:"bytes,8,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"` // JSON schema bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorManifest) Reset() {
	*x = CollectorManifest{}
	mi := &file_internal_proto_recon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorManifest) ProtoMessage() {}

func (x *CollectorManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorManifest.ProtoReflect.Descriptor instead.
func (*CollectorManifest) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{6}
}

func (x *CollectorManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectorManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CollectorManifest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CollectorManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CollectorManifest) GetReads() []string {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *CollectorManifest) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *CollectorManifest) GetParamsSchema() []byte {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

func (x *CollectorManifest) GetOutputSchema() []byte {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

type CollectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Collector      string                 `protobuf:"bytes,2,opt,name=collector,proto3" json:"collector,omitempty"`
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_internal_proto_recon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{7}
}

func (x *CollectRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CollectRequest) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *CollectRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CollectRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_internal_proto_recon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{8}
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ConfigUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for future hub-pushed agent config changes (e.g., log level).
	// No mutating semantics on the host itself.
	Values        map[string]string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_internal_proto_recon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigUpdate) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CollectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=recon.v1.Status" json:"status,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ArtifactRefs  []string               `protobuf:"bytes,5,rep,name=artifact_refs,json=artifactRefs,proto3" json:"artifact_refs,omitempty"`
	Hints         []*Hint                `protobuf:"bytes,6,rep,name=hints,proto3" json:"hints,omitempty"`
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResult) Reset() {
	*x = CollectResult{}
	mi := &file_internal_proto_recon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResult) ProtoMessage() {}

func (x *CollectResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResult.ProtoReflect.Descriptor instead.
func (*CollectResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{10}
}

func (x *CollectResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CollectResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *CollectResult) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *CollectResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CollectResult) GetArtifactRefs() []string {
	if x != nil {
		return x.ArtifactRefs
	}
	return nil
}

func (x *CollectResult) GetHints() []*Hint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *CollectResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CollectResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CollectResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Hint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // info | warn | error
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // e.g. "service.inactive"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EvidenceJson  []byte                 `protobuf:"bytes,4,opt,name=evidence_json,json=evidenceJson,proto3" json:"evidence_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hint) Reset() {
	*x = Hint{}
	mi := &file_internal_proto_recon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{11}
}

func (x *Hint) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Hint) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Hint) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Hint) GetEvidenceJson() []byte {
	if x != nil {
		return x.EvidenceJson
	}
	return nil
}

type ArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // e.g. "journalctl.kubelet.txt"
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunk) Reset() {
	*x = ArtifactChunk{}
	mi := &file_internal_proto_recon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunk) ProtoMessage() {}

func (x *ArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunk.ProtoReflect.Descriptor instead.
func (*ArtifactChunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_recon_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ArtifactChunk) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactChunk) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ArtifactChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArtifactChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

var File_internal_proto_recon_proto protoreflect.FileDescriptor

const file_internal_proto_recon_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/recon.proto\x12\brecon.v1\"l\n" +
	"\rEnrollRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\"V\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12\x1c\n" +
	"\n" +
	"hub_ca_pem\x18\x02 \x01(\fR\bhubCaPem\"\xdd\x01\n" +
	"\bAgentMsg\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.recon.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.recon.v1.HeartbeatH\x00R\theartbeat\x121\n" +
	"\x06result\x18\x03 \x01(\v2\x17.recon.v1.CollectResultH\x00R\x06result\x125\n" +
	"\bartifact\x18\x04 \x01(\v2\x17.recon.v1.ArtifactChunkH\x00R\bartifactB\t\n" +
	"\apayload\"\xae\x01\n" +
	"\x06HubMsg\x124\n" +
	"\acollect\x18\x01 \x01(\v2\x18.recon.v1.CollectRequestH\x00R\acollect\x121\n" +
	"\x06cancel\x18\x02 \x01(\v2\x17.recon.v1.CancelRequestH\x00R\x06cancel\x120\n" +
	"\x06config\x18\x03 \x01(\v2\x16.recon.v1.ConfigUpdateH\x00R\x06configB\t\n" +
	"\apayload\"\xd5\x02\n" +
	"\x05Hello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x123\n" +
	"\x06labels\x18\x03 \x03(\v2\x1b.recon.v1.Hello.LabelsEntryR\x06labels\x12;\n" +
	"\n" +
	"collectors\x18\x04 \x03(\v2\x1b.recon.v1.CollectorManifestR\n" +
	"collectors\x120\n" +
	"\x05facts\x18\x05 \x03(\v2\x1a.recon.v1.Hello.FactsEntryR\x05facts\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"FactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\buptime_s\x18\x02 \x01(\x03R\auptimeS\x12\x17\n" +
	"\ats_unix\x18\x03 \x01(\x03R\x06tsUnix\"\xfb\x01\n" +
	"\x11CollectorManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05reads\x18\x05 \x03(\tR\x05reads\x12\x1a\n" +
	"\brequires\x18\x06 \x03(\tR\brequires\x12#\n" +
	"\rparams_schema\x18\a \x01(\fR\fparamsSchema\x12#\n" +
	"\routput_schema\x18\b \x01(\fR\foutputSchema\"\xef\x01\n" +
	"\x0eCollectRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tcollector\x18\x02 \x01(\tR\tcollector\x12<\n" +
	"\x06params\x18\x03 \x03(\v2$.recon.v1.CollectRequest.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x85\x01\n" +
	"\fConfigUpdate\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".recon.v1.ConfigUpdate.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x02\n" +
	"\rCollectResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.recon.v1.StatusR\x06status\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12#\n" +
	"\rartifact_refs\x18\x05 \x03(\tR\fartifactRefs\x12$\n" +
	"\x05hints\x18\x06 \x03(\v2\x0e.recon.v1.HintR\x05hints\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\"u\n" +
	"\x04Hint\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\revidence_json\x18\x04 \x01(\fR\fevidenceJson\"\xb7\x01\n" +
	"\rArtifactChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\a \x01(\bR\x04last*j\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x042w\n" +
	"\x03Hub\x12;\n" +
	"\x06Enroll\x12\x17.recon.v1.EnrollRequest\x1a\x18.recon.v1.EnrollResponse\x123\n" +
	"\aConnect\x12\x12.recon.v1.AgentMsg\x1a\x10.recon.v1.HubMsg(\x010\x01B2Z0github.com/vasyakrg/recon/internal/proto;reconpbb\x06proto3"

var (
	file_internal_proto_recon_proto_rawDescOnce sync.Once
	file_internal_proto_recon_proto_rawDescData []byte
)

func file_internal_proto_recon_proto_rawDescGZIP() []byte {
	file_internal_proto_recon_proto_rawDescOnce.Do(func() {
		file_internal_proto_recon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_recon_proto_rawDesc), len(file_internal_proto_recon_proto_rawDesc)))
	})
	return file_internal_proto_recon_proto_rawDescData
}

var file_internal_proto_recon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_recon_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_recon_proto_goTypes = []any{
	(Status)(0),               // 0: recon.v1.Status
	(*EnrollRequest)(nil),     // 1: recon.v1.EnrollRequest
	(*EnrollResponse)(nil),    // 2: recon.v1.EnrollResponse
	(*AgentMsg)(nil),          // 3: recon.v1.AgentMsg
	(*HubMsg)(nil),            // 4: recon.v1.HubMsg
	(*Hello)(nil),             // 5: recon.v1.Hello
	(*Heartbeat)(nil),         // 6: recon.v1.Heartbeat
	(*CollectorManifest)(nil), // 7: recon.v1.CollectorManifest
	(*CollectRequest)(nil),    // 8: recon.v1.CollectRequest
	(*CancelRequest)(nil),     // 9: recon.v1.CancelRequest
	(*ConfigUpdate)(nil),      // 10: recon.v1.ConfigUpdate
	(*CollectResult)(nil),     // 11: recon.v1.CollectResult
	(*Hint)(nil),              // 12: recon.v1.Hint
	(*ArtifactChunk)(nil),     // 13: recon.v1.ArtifactChunk
	nil,                       // 14: recon.v1.Hello.LabelsEntry
	nil,                       // 15: recon.v1.Hello.FactsEntry
	nil,                       // 16: recon.v1.CollectRequest.ParamsEntry
	nil,                       // 17: recon.v1.ConfigUpdate.ValuesEntry
}
var file_internal_proto_recon_proto_depIdxs = []int32{
	5,  // 0: recon.v1.AgentMsg.hello:type_name -> recon.v1.Hello
	6,  // 1: recon.v1.AgentMsg.heartbeat:type_name -> recon.v1.Heartbeat
	11, // 2: recon.v1.AgentMsg.result:type_name -> recon.v1.CollectResult
	13, // 3: recon.v1.AgentMsg.artifact:type_name -> recon.v1.ArtifactChunk
	8,  // 4: recon.v1.HubMsg.collect:type_name -> recon.v1.CollectRequest
	9,  // 5: recon.v1.HubMsg.cancel:type_name -> recon.v1.CancelRequest
	10, // 6: recon.v1.HubMsg.config:type_name -> recon.v1.ConfigUpdate
	14, // 7: recon.v1.Hello.labels:type_name -> recon.v1.Hello.LabelsEntry
	7,  // 8: recon.v1.Hello.collectors:type_name -> recon.v1.CollectorManifest
	15, // 9: recon.v1.Hello.facts:type_name -> recon.v1.Hello.FactsEntry
	16, // 10: recon.v1.CollectRequest.params:type_name -> recon.v1.CollectRequest.ParamsEntry
	17, // 11: recon.v1.ConfigUpdate.values:type_name -> recon.v1.ConfigUpdate.ValuesEntry
	0,  // 12: recon.v1.CollectResult.status:type_name -> recon.v1.Status
	12, // 13: recon.v1.CollectResult.hints:type_name -> recon.v1.Hint
	1,  // 14: recon.v1.Hub.Enroll:input_type -> recon.v1.EnrollRequest
	3,  // 15: recon.v1.Hub.Connect:input_type -> recon.v1.AgentMsg
	2,  // 16: recon.v1.Hub.Enroll:output_type -> recon.v1.EnrollResponse
	4,  // 17: recon.v1.Hub.Connect:output_type -> recon.v1.HubMsg
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_proto_recon_proto_init() }
func file_internal_proto_recon_proto_init() {
	if File_internal_proto_recon_proto != nil {
		return
	}
	file_internal_proto_recon_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMsg_Hello)(nil),
		(*AgentMsg_Heartbeat)(nil),
		(*AgentMsg_Result)(nil),
		(*AgentMsg_Artifact)(nil),
	}
	file_internal_proto_recon_proto_msgTypes[3].OneofWrappers = []any{
		(*HubMsg_Collect)(nil),
		(*HubMsg_Cancel)(nil),
		(*HubMsg_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_recon_proto_rawDesc), len(file_internal_proto_recon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_recon_proto_goTypes,
		DependencyIndexes: file_internal_proto_recon_proto_depIdxs,
		EnumInfos:         file_internal_proto_recon_proto_enumTypes,
		MessageInfos:      file_internal_proto_recon_proto_msgTypes,
	}.Build()
	File_internal_proto_recon_proto = out.File
	file_internal_proto_recon_proto_goTypes = nil
	file_internal_proto_recon_proto_depIdxs = nil
}
