server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Long-cache static Nuxt assets; hashed filenames = safe to cache forever.
    location /site/_nuxt/ {
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location = /site {
        return 301 /site/;
    }

    location /site/ {
        try_files $uri $uri/ /site/index.html;
    }

    location = / {
        return 302 /site/;
    }
}
